# Generated by Django 4.2.2 on 2024-03-15 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)]),
        ),
    ]
