# Generated by Django 4.2.2 on 2024-03-15 22:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_cta_text',
            field=models.CharField(max_length=254, null=True, verbose_name='Button Text (About Page)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_cta_text',
            field=models.CharField(max_length=254, null=True, verbose_name='Button Text (Gallery Page)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_text',
            field=models.CharField(max_length=254, null=True, verbose_name='Gallery Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_banner',
            field=models.ForeignKey(blank=True, help_text='Banner image (landscape)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='menu_cta_text',
            field=models.CharField(max_length=254, null=True, verbose_name='Button Text (Menu Page)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcome_img',
            field=models.ForeignKey(blank=True, help_text='Welcome image (portrait)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcome_paragraph',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcome_title',
            field=models.CharField(max_length=254, null=True, verbose_name='Welcome Title'),
        ),
    ]
