# Generated by Django 4.2.2 on 2024-03-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gallerypage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryPage',
        ),
    ]
