# Generated by Django 4.2.2 on 2024-03-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Apartment / Building'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street1',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
